### PR TITLE
update pins

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@pkgw I am not sure what that error means :confused:

**Comment by pkgw** [comment]
@ocefpaf Hmm, I'm not sure. I think it's related to this line of output from conda-build:

```
Warning: Unrecognized source format. Source file will be copied to the SRC_DIR
```

But the source format hasn't changed. So my guess is that it's a transient failure — can you retry the build? I don't seem to have permissions to do so.

Alternately, maybe conda-build somehow got *less* clever about unpacking source tarballs. I note that the download doesn't have a filename extension. But, again, this *used* to work ...

**Comment by pkgw** [comment]
@ocefpaf Hmm, I'm not sure. I think it's related to this line of output from conda-build:

```
Warning: Unrecognized source format. Source file will be copied to the SRC_DIR
```

But the source format hasn't changed. So my guess is that it's a transient failure — can you retry the build? I don't seem to have permissions to do so.

Alternately, maybe conda-build somehow got *less* clever about unpacking source tarballs. I note that the download doesn't have a filename extension. But, again, this *used* to work ...

**Comment by pkgw** [comment]
@ocefpaf Hmm, I'm not sure. I think it's related to this line of output from conda-build:

```
Warning: Unrecognized source format. Source file will be copied to the SRC_DIR
```

But the source format hasn't changed. So my guess is that it's a transient failure — can you retry the build? I don't seem to have permissions to do so.

Alternately, maybe conda-build somehow got *less* clever about unpacking source tarballs. I note that the download doesn't have a filename extension. But, again, this *used* to work ...

**Comment by ocefpaf** [comment]
> I don't seem to have permissions to do so.

That is odd. You should have.

> Alternately, maybe conda-build somehow got *less* clever about unpacking source tarballs. I note that the download doesn't have a filename extension. But, again, this *used* to work ...

I removed the `fn` and that forces conda to use from the URL. So I guess that was it, we need to be explicit in this case and give conda an output name.

**Comment by pkgw** [comment]
Ah, I should have actually looked at the diffs. I bet the `fn` change is the cause yes.

On my side, it looks like the CircleCI login on my browser was messed up. I have the standard set of controls now.

**Comment by pkgw** [comment]
Whoops, I never merged this, but now it is superseded by #3. Thanks @ocefpaf!

**Comment by ocefpaf** [comment]
Thanks! Looking forward to try latest tectonic!

**Pull request closed without merging**
