### PR TITLE
[wip] add pdf generation example

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Notes:
- investigating #21
- minimal reproduction of test from https://github.com/krassowski/jupyterlab-lsp/pull/323

### CODE REVIEW

**Comment by bollwyvl** [comment]
Of note... I notice this doesn't ship all the licenses for the vendored static content... hopefully https://github.com/conda-forge/staged-recipes/pull/11844 will land, which can substantially reduce the complexity of getting up to (and staying in) compliance...

**Comment by bollwyvl** [comment]
Hooray/boo, we've reproduced the issue... @pkgw are the command line flags, or compile options, we might be able to use to get more details? I'm rather a rust noob, though have gotten a few packages to build more-or-less predictably...

**Comment by bollwyvl** [comment]
Hooray tests!

**Comment by pkgw** [comment]
@bollwyvl Having trouble with them though :grimacing: Hopefully they'll help get the packages straightened out though ...

**Comment by bollwyvl** [comment]
Really appreciate you looking into this... just reading tea leaves, but maybe osx needs https://github.com/conda-forge/libiconv-feedstock?

**Comment by pkgw** [comment]
I have cherry-picked this commits into the pull request to bump to 0.1.14, #27, which I am hoping maybe helps with the issues here (for no concrete reason, alas).

**Pull request closed without merging**
